let lumoraNews=[],lumoraShowAll=false;
const escN=v=>String(v??"").replace(/[&<>"\']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","\'":"&#039;"}[m]));
function normN(raw){const arr=Array.isArray(raw)?raw:(raw?.data||raw?.events||raw?.news||[]);return arr.map((x,i)=>{const t=x.timestamp||x.datetime||x.dateTime||x.time||x.releaseTime||x.date;const d=typeof t==="number"?new Date(t<2e12?t*1000:t):new Date(t);const q=String(x.impact||x.importance||"medium").toLowerCase();return{id:String(x.id||`${x.currency||"USD"}-${x.title||x.event||"news"}-${d.getTime()}-${i}`),country:x.country||"US",currency:x.currency||"USD",title:x.title||x.event||x.name||"Economic News",impact:q.includes("high")||q==="3"?"high":q.includes("low")||q==="1"?"low":"medium",time:d}}).filter(x=>Number.isFinite(x.time.getTime())&&(x.currency==="USD"||x.country==="US")).sort((a,b)=>a.time-b.time)}
function demoN(){const d=new Date();d.setSeconds(0,0);return[{id:"demo-cpi",country:"US",currency:"USD",title:"Core CPI m/m",impact:"high",time:new Date(d.getTime()+31*60000)},{id:"demo-claims",country:"US",currency:"USD",title:"Initial Jobless Claims",impact:"medium",time:new Date(d.getTime()+49*60000)}]}
async function getN(){try{const r=await fetch("/api/news",{cache:"no-store"});if(!r.ok)throw 0;const d=normN(await r.json());if(d.length){localStorage.setItem("lumora_news_v5",JSON.stringify(d.map(n=>({...n,time:n.time.toISOString()}))));return d}}catch(e){}try{const d=normN(JSON.parse(localStorage.getItem("lumora_news_v5")||"[]"));if(d.length)return d}catch(e){}return demoN()}
function cdN(ms){ms=Math.max(0,ms);let s=Math.floor(ms/1000),h=Math.floor(s/3600),m=Math.floor(s%3600/60),x=s%60;return[h,m,x].map(v=>String(v).padStart(2,"0")).join(":")}
function renderN(){const list=document.getElementById("newsList"),empty=document.getElementById("newsEmpty");if(!list)return;const now=Date.now(),end=now+3600000;lumoraNews=lumoraNews.filter(n=>n.time.getTime()>now&&n.time.getTime()<=end);const shown=lumoraShowAll?lumoraNews:lumoraNews.slice(0,3);list.innerHTML="";empty.hidden=shown.length>0;shown.forEach(n=>{const e=document.createElement("div");e.className="news-item";e.innerHTML=`<div class="news-country">${escN(n.country)}</div><div class="news-copy"><b>${escN(n.currency)} — ${escN(n.title)}</b><small>Potential impact on XAU/USD</small><label class="news-impact ${n.impact}">${n.impact} impact</label></div><div class="news-count"><b>${cdN(n.time.getTime()-now)}</b><small>Hours　 Minutes　 Seconds</small></div>`;list.appendChild(e)})}
async function startN(){lumoraNews=await getN();renderN();setInterval(renderN,1000);setInterval(async()=>{lumoraNews=await getN();renderN()},300000)}
document.getElementById("viewNews")?.addEventListener("click",()=>{lumoraShowAll=!lumoraShowAll;document.getElementById("viewNews").textContent=lumoraShowAll?"Show Less":"View All";renderN()});startN();
